const players = [
  {
    "id": 6,
    "team_id": 4,
    "full_name": "Aaron Wan-Bissaka",
    "age": "22",
    "birthday": "880531200",
    "league": "Premier League",
    "season": "2018/2019",
    "position": "Midfielder",
    "current_club": "Crystal Palace",
    "minutes_played_overall": "3135",
    "minutes_played_home": "1605",
    "minutes_played_away": "1530",
    "nationality": "England",
    "appearances_overall": "35",
    "appearances_home": "18",
    "appearances_away": "17",
    "goals_overall": "0",
    "goals_home": "0",
    "goals_away": "0",
    "assists_overall": "3",
    "assists_home": "1",
    "assists_away": "2",
    "penalty_goals": "0",
    "penalty_misses": "0",
    "clean_sheets_overall": "12",
    "clean_sheets_home": "7",
    "clean_sheets_away": "5",
    "conceded_overall": "41",
    "conceded_home": "17",
    "conceded_away": "24",
    "yellow_cards_overall": "5",
    "red_cards_overall": "1",
    "goals_involved_per90_overall": "0.09",
    "assists_per90_overall": "0.09",
    "goals_per90_overall": "0",
    "goals_per90_home": "0",
    "goals_per90_away": "0",
    "min_per_goal_overall": "0",
    "conceded_per90_overall": "1.18",
    "min_per_conceded_overall": "76",
    "min_per_match": "90",
    "min_per_card_overall": "523",
    "min_per_assist_overall": "1045",
    "cards_per90_overall": "0.17",
    "rank_in_league_top_attackers": "312",
    "rank_in_league_top_midfielders": "160",
    "rank_in_league_top_defenders": "-1",
    "rank_in_club_top_scorer": "22"
  },
  {
    "id": 28,
    "team_id": 4,
    "full_name": "Alexander S├╕rloth",
    "age": "24",
    "birthday": "818150400",
    "league": "Premier League",
    "season": "2018/2019",
    "position": "Forward",
    "current_club": "Crystal Palace",
    "minutes_played_overall": "173",
    "minutes_played_home": "121",
    "minutes_played_away": "52",
    "nationality": "Norway",
    "appearances_overall": "12",
    "appearances_home": "8",
    "appearances_away": "4",
    "goals_overall": "0",
    "goals_home": "0",
    "goals_away": "0",
    "assists_overall": "0",
    "assists_home": "0",
    "assists_away": "0",
    "penalty_goals": "0",
    "penalty_misses": "0",
    "clean_sheets_overall": "4",
    "clean_sheets_home": "3",
    "clean_sheets_away": "1",
    "conceded_overall": "1",
    "conceded_home": "0",
    "conceded_away": "1",
    "yellow_cards_overall": "0",
    "red_cards_overall": "0",
    "goals_involved_per90_overall": "0",
    "assists_per90_overall": "0",
    "goals_per90_overall": "0",
    "goals_per90_home": "0",
    "goals_per90_away": "0",
    "min_per_goal_overall": "0",
    "conceded_per90_overall": "0.52",
    "min_per_conceded_overall": "173",
    "min_per_match": "14",
    "min_per_card_overall": "0",
    "min_per_assist_overall": "0",
    "cards_per90_overall": "0",
    "rank_in_league_top_attackers": "-1",
    "rank_in_league_top_midfielders": "-1",
    "rank_in_league_top_defenders": "-1",
    "rank_in_club_top_scorer": "17"
  },
  {
    "id": 49,
    "team_id": 4,
    "full_name": "Andros Townsend",
    "age": "29",
    "birthday": "679647600",
    "league": "Premier League",
    "season": "2018/2019",
    "position": "Midfielder",
    "current_club": "Crystal Palace",
    "minutes_played_overall": "3018",
    "minutes_played_home": "1571",
    "minutes_played_away": "1447",
    "nationality": "England",
    "appearances_overall": "38",
    "appearances_home": "19",
    "appearances_away": "19",
    "goals_overall": "6",
    "goals_home": "2",
    "goals_away": "4",
    "assists_overall": "4",
    "assists_home": "2",
    "assists_away": "2",
    "penalty_goals": "0",
    "penalty_misses": "0",
    "clean_sheets_overall": "12",
    "clean_sheets_home": "7",
    "clean_sheets_away": "5",
    "conceded_overall": "44",
    "conceded_home": "20",
    "conceded_away": "24",
    "yellow_cards_overall": "1",
    "red_cards_overall": "0",
    "goals_involved_per90_overall": "0.3",
    "assists_per90_overall": "0.12",
    "goals_per90_overall": "0.18",
    "goals_per90_home": "0.11",
    "goals_per90_away": "0.25",
    "min_per_goal_overall": "503",
    "conceded_per90_overall": "1.31",
    "min_per_conceded_overall": "69",
    "min_per_match": "79",
    "min_per_card_overall": "3018",
    "min_per_assist_overall": "755",
    "cards_per90_overall": "0.03",
    "rank_in_league_top_attackers": "102",
    "rank_in_league_top_midfielders": "127",
    "rank_in_league_top_defenders": "-1",
    "rank_in_club_top_scorer": "3"
  },
  {
    "id": 70,
    "team_id": 4,
    "full_name": "Bakary Sako",
    "age": "32",
    "birthday": "578041200",
    "league": "Premier League",
    "season": "2018/2019",
    "position": "Midfielder",
    "current_club": "Crystal Palace",
    "minutes_played_overall": "25",
    "minutes_played_home": "8",
    "minutes_played_away": "17",
    "nationality": "Mali",
    "appearances_overall": "4",
    "appearances_home": "3",
    "appearances_away": "1",
    "goals_overall": "0",
    "goals_home": "0",
    "goals_away": "0",
    "assists_overall": "0",
    "assists_home": "0",
    "assists_away": "0",
    "penalty_goals": "0",
    "penalty_misses": "0",
    "clean_sheets_overall": "1",
    "clean_sheets_home": "1",
    "clean_sheets_away": "0",
    "conceded_overall": "0",
    "conceded_home": "0",
    "conceded_away": "0",
    "yellow_cards_overall": "0",
    "red_cards_overall": "0",
    "goals_involved_per90_overall": "0",
    "assists_per90_overall": "0",
    "goals_per90_overall": "0",
    "goals_per90_home": "0",
    "goals_per90_away": "0",
    "min_per_goal_overall": "0",
    "conceded_per90_overall": "0",
    "min_per_conceded_overall": "0",
    "min_per_match": "6",
    "min_per_card_overall": "0",
    "min_per_assist_overall": "0",
    "cards_per90_overall": "0",
    "rank_in_league_top_attackers": "-1",
    "rank_in_league_top_midfielders": "-1",
    "rank_in_league_top_defenders": "-1",
    "rank_in_club_top_scorer": "23"
  },
  {
    "id": 109,
    "team_id": 4,
    "full_name": "Cheikhou Kouyat├⌐",
    "age": "30",
    "birthday": "630230400",
    "league": "Premier League",
    "season": "2018/2019",
    "position": "Midfielder",
    "current_club": "Crystal Palace",
    "minutes_played_overall": "1897",
    "minutes_played_home": "865",
    "minutes_played_away": "1032",
    "nationality": "Senegal",
    "appearances_overall": "31",
    "appearances_home": "14",
    "appearances_away": "17",
    "goals_overall": "0",
    "goals_home": "0",
    "goals_away": "0",
    "assists_overall": "2",
    "assists_home": "1",
    "assists_away": "1",
    "penalty_goals": "0",
    "penalty_misses": "0",
    "clean_sheets_overall": "11",
    "clean_sheets_home": "6",
    "clean_sheets_away": "5",
    "conceded_overall": "24",
    "conceded_home": "7",
    "conceded_away": "17",
    "yellow_cards_overall": "3",
    "red_cards_overall": "0",
    "goals_involved_per90_overall": "0.09",
    "assists_per90_overall": "0.09",
    "goals_per90_overall": "0",
    "goals_per90_home": "0",
    "goals_per90_away": "0",
    "min_per_goal_overall": "0",
    "conceded_per90_overall": "1.14",
    "min_per_conceded_overall": "79",
    "min_per_match": "61",
    "min_per_card_overall": "632",
    "min_per_assist_overall": "949",
    "cards_per90_overall": "0.14",
    "rank_in_league_top_attackers": "323",
    "rank_in_league_top_midfielders": "161",
    "rank_in_league_top_defenders": "-1",
    "rank_in_club_top_scorer": "20"
  },
  {
    "id": 115,
    "team_id": 4,
    "full_name": "Christian Benteke",
    "age": "29",
    "birthday": "660211200",
    "league": "Premier League",
    "season": "2018/2019",
    "position": "Forward",
    "current_club": "Crystal Palace",
    "minutes_played_overall": "813",
    "minutes_played_home": "526",
    "minutes_played_away": "287",
    "nationality": "Belgium",
    "appearances_overall": "16",
    "appearances_home": "10",
    "appearances_away": "6",
    "goals_overall": "1",
    "goals_home": "0",
    "goals_away": "1",
    "assists_overall": "1",
    "assists_home": "0",
    "assists_away": "1",
    "penalty_goals": "0",
    "penalty_misses": "0",
    "clean_sheets_overall": "5",
    "clean_sheets_home": "3",
    "clean_sheets_away": "2",
    "conceded_overall": "10",
    "conceded_home": "6",
    "conceded_away": "4",
    "yellow_cards_overall": "1",
    "red_cards_overall": "0",
    "goals_involved_per90_overall": "0.22",
    "assists_per90_overall": "0.11",
    "goals_per90_overall": "0.11",
    "goals_per90_home": "0",
    "goals_per90_away": "0.31",
    "min_per_goal_overall": "813",
    "conceded_per90_overall": "1.11",
    "min_per_conceded_overall": "81",
    "min_per_match": "51",
    "min_per_card_overall": "813",
    "min_per_assist_overall": "813",
    "cards_per90_overall": "0.11",
    "rank_in_league_top_attackers": "149",
    "rank_in_league_top_midfielders": "141",
    "rank_in_league_top_defenders": "-1",
    "rank_in_club_top_scorer": "10"
  },
  {
    "id": 123,
    "team_id": 4,
    "full_name": "Connor Wickham",
    "age": "27",
    "birthday": "733564800",
    "league": "Premier League",
    "season": "2018/2019",
    "position": "Forward",
    "current_club": "Crystal Palace",
    "minutes_played_overall": "61",
    "minutes_played_home": "49",
    "minutes_played_away": "12",
    "nationality": "England",
    "appearances_overall": "6",
    "appearances_home": "3",
    "appearances_away": "3",
    "goals_overall": "0",
    "goals_home": "0",
    "goals_away": "0",
    "assists_overall": "1",
    "assists_home": "0",
    "assists_away": "1",
    "penalty_goals": "0",
    "penalty_misses": "0",
    "clean_sheets_overall": "2",
    "clean_sheets_home": "1",
    "clean_sheets_away": "1",
    "conceded_overall": "0",
    "conceded_home": "0",
    "conceded_away": "0",
    "yellow_cards_overall": "0",
    "red_cards_overall": "0",
    "goals_involved_per90_overall": "1.48",
    "assists_per90_overall": "1.48",
    "goals_per90_overall": "0",
    "goals_per90_home": "0",
    "goals_per90_away": "0",
    "min_per_goal_overall": "0",
    "conceded_per90_overall": "0",
    "min_per_conceded_overall": "0",
    "min_per_match": "10",
    "min_per_card_overall": "0",
    "min_per_assist_overall": "61",
    "cards_per90_overall": "0",
    "rank_in_league_top_attackers": "-1",
    "rank_in_league_top_midfielders": "-1",
    "rank_in_league_top_defenders": "-1",
    "rank_in_club_top_scorer": "16"
  },
  {
    "id": 242,
    "team_id": 4,
    "full_name": "Ja├»ro Riedewald",
    "age": "24",
    "birthday": "842252400",
    "league": "Premier League",
    "season": "2018/2019",
    "position": "Defender",
    "current_club": "Crystal Palace",
    "minutes_played_overall": "0",
    "minutes_played_home": "0",
    "minutes_played_away": "0",
    "nationality": "Netherlands",
    "appearances_overall": "0",
    "appearances_home": "0",
    "appearances_away": "0",
    "goals_overall": "0",
    "goals_home": "0",
    "goals_away": "0",
    "assists_overall": "0",
    "assists_home": "0",
    "assists_away": "0",
    "penalty_goals": "0",
    "penalty_misses": "0",
    "clean_sheets_overall": "0",
    "clean_sheets_home": "0",
    "clean_sheets_away": "0",
    "conceded_overall": "0",
    "conceded_home": "0",
    "conceded_away": "0",
    "yellow_cards_overall": "0",
    "red_cards_overall": "0",
    "goals_involved_per90_overall": "0",
    "assists_per90_overall": "0",
    "goals_per90_overall": "0",
    "goals_per90_home": "0",
    "goals_per90_away": "0",
    "min_per_goal_overall": "0",
    "conceded_per90_overall": "0",
    "min_per_conceded_overall": "0",
    "min_per_match": "0",
    "min_per_card_overall": "0",
    "min_per_assist_overall": "0",
    "cards_per90_overall": "0",
    "rank_in_league_top_attackers": "-1",
    "rank_in_league_top_midfielders": "-1",
    "rank_in_league_top_defenders": "-1",
    "rank_in_club_top_scorer": "-1"
  },
  {
    "id": 246,
    "team_id": 4,
    "full_name": "James McArthur",
    "age": "33",
    "birthday": "560588400",
    "league": "Premier League",
    "season": "2018/2019",
    "position": "Midfielder",
    "current_club": "Crystal Palace",
    "minutes_played_overall": "3071",
    "minutes_played_home": "1506",
    "minutes_played_away": "1565",
    "nationality": "Scotland",
    "appearances_overall": "38",
    "appearances_home": "19",
    "appearances_away": "19",
    "goals_overall": "3",
    "goals_home": "1",
    "goals_away": "2",
    "assists_overall": "6",
    "assists_home": "1",
    "assists_away": "5",
    "penalty_goals": "0",
    "penalty_misses": "0",
    "clean_sheets_overall": "12",
    "clean_sheets_home": "7",
    "clean_sheets_away": "5",
    "conceded_overall": "44",
    "conceded_home": "19",
    "conceded_away": "25",
    "yellow_cards_overall": "7",
    "red_cards_overall": "0",
    "goals_involved_per90_overall": "0.26",
    "assists_per90_overall": "0.18",
    "goals_per90_overall": "0.09",
    "goals_per90_home": "0.06",
    "goals_per90_away": "0.12",
    "min_per_goal_overall": "1024",
    "conceded_per90_overall": "1.29",
    "min_per_conceded_overall": "70",
    "min_per_match": "81",
    "min_per_card_overall": "439",
    "min_per_assist_overall": "512",
    "cards_per90_overall": "0.21",
    "rank_in_league_top_attackers": "172",
    "rank_in_league_top_midfielders": "74",
    "rank_in_league_top_defenders": "-1",
    "rank_in_club_top_scorer": "7"
  },
  {
    "id": 250,
    "team_id": 4,
    "full_name": "James Tomkins",
    "age": "31",
    "birthday": "607161600",
    "league": "Premier League",
    "season": "2018/2019",
    "position": "Defender",
    "current_club": "Crystal Palace",
    "minutes_played_overall": "2563",
    "minutes_played_home": "1140",
    "minutes_played_away": "1423",
    "nationality": "England",
    "appearances_overall": "29",
    "appearances_home": "13",
    "appearances_away": "16",
    "goals_overall": "1",
    "goals_home": "0",
    "goals_away": "1",
    "assists_overall": "1",
    "assists_home": "0",
    "assists_away": "1",
    "penalty_goals": "0",
    "penalty_misses": "0",
    "clean_sheets_overall": "10",
    "clean_sheets_home": "5",
    "clean_sheets_away": "5",
    "conceded_overall": "34",
    "conceded_home": "12",
    "conceded_away": "22",
    "yellow_cards_overall": "6",
    "red_cards_overall": "0",
    "goals_involved_per90_overall": "0.07",
    "assists_per90_overall": "0.04",
    "goals_per90_overall": "0.04",
    "goals_per90_home": "0",
    "goals_per90_away": "0.06",
    "min_per_goal_overall": "2563",
    "conceded_per90_overall": "1.19",
    "min_per_conceded_overall": "75",
    "min_per_match": "88",
    "min_per_card_overall": "427",
    "min_per_assist_overall": "2563",
    "cards_per90_overall": "0.21",
    "rank_in_league_top_attackers": "234",
    "rank_in_league_top_midfielders": "215",
    "rank_in_league_top_defenders": "63",
    "rank_in_club_top_scorer": "9"
  },
  {
    "id": 266,
    "team_id": 4,
    "full_name": "Jeffrey Schlupp",
    "age": "27",
    "birthday": "725097600",
    "league": "Premier League",
    "season": "2018/2019",
    "position": "Defender",
    "current_club": "Crystal Palace",
    "minutes_played_overall": "1665",
    "minutes_played_home": "849",
    "minutes_played_away": "816",
    "nationality": "Ghana",
    "appearances_overall": "30",
    "appearances_home": "14",
    "appearances_away": "16",
    "goals_overall": "4",
    "goals_home": "1",
    "goals_away": "3",
    "assists_overall": "1",
    "assists_home": "1",
    "assists_away": "0",
    "penalty_goals": "0",
    "penalty_misses": "0",
    "clean_sheets_overall": "8",
    "clean_sheets_home": "4",
    "clean_sheets_away": "4",
    "conceded_overall": "24",
    "conceded_home": "11",
    "conceded_away": "13",
    "yellow_cards_overall": "1",
    "red_cards_overall": "0",
    "goals_involved_per90_overall": "0.27",
    "assists_per90_overall": "0.05",
    "goals_per90_overall": "0.22",
    "goals_per90_home": "0.11",
    "goals_per90_away": "0.33",
    "min_per_goal_overall": "416",
    "conceded_per90_overall": "1.3",
    "min_per_conceded_overall": "69",
    "min_per_match": "56",
    "min_per_card_overall": "1665",
    "min_per_assist_overall": "1665",
    "cards_per90_overall": "0.05",
    "rank_in_league_top_attackers": "89",
    "rank_in_league_top_midfielders": "209",
    "rank_in_league_top_defenders": "86",
    "rank_in_club_top_scorer": "5"
  }
]

export default players